In [1]:
from google.colab import files
uploaded = files.upload()

Saving Bank_churn_modelling.csv to Bank_churn_modelling.csv


In [2]:
import pandas as pd
import numpy as np
import io

In [3]:
df = pd.read_csv(io.BytesIO(uploaded['Bank_churn_modelling.csv']))

In [4]:
df

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [6]:
df = df.drop('RowNumber', axis=1)

In [8]:
df = df.drop('CustomerId', axis=1)

In [10]:
df = df.drop('Surname', axis=1)

In [11]:
df

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [15]:
print(pd.get_dummies(df))

      CreditScore  Age  Tenure  ...  Geography_Spain  Gender_Female  Gender_Male
0             619   42       2  ...                0              1            0
1             608   41       1  ...                1              1            0
2             502   42       8  ...                0              1            0
3             699   39       1  ...                0              1            0
4             850   43       2  ...                1              1            0
...           ...  ...     ...  ...              ...            ...          ...
9995          771   39       5  ...                0              0            1
9996          516   35      10  ...                0              0            1
9997          709   36       7  ...                0              1            0
9998          772   42       3  ...                0              0            1
9999          792   28       4  ...                0              1            0

[10000 rows x 14 columns]


In [16]:
df = pd.get_dummies(df)

In [17]:
df

CreditScore  Age  Tenure  ...  Geography_Spain  Gender_Female  Gender_Male
0             619   42       2  ...                0              1            0
1             608   41       1  ...                1              1            0
2             502   42       8  ...                0              1            0
3             699   39       1  ...                0              1            0
4             850   43       2  ...                1              1            0
...           ...  ...     ...  ...              ...            ...          ...
9995          771   39       5  ...                0              0            1
9996          516   35      10  ...                0              0            1
9997          709   36       7  ...                0              1            0
9998          772   42       3  ...                0              0            1
9999          792   28       4  ...                0              1            0

[10000 rows x 14 columns]

In [20]:
df2 = df

In [21]:
X_train = df2.drop('Exited', axis=1)

In [22]:
X_train

CreditScore  Age  Tenure  ...  Geography_Spain  Gender_Female  Gender_Male
0             619   42       2  ...                0              1            0
1             608   41       1  ...                1              1            0
2             502   42       8  ...                0              1            0
3             699   39       1  ...                0              1            0
4             850   43       2  ...                1              1            0
...           ...  ...     ...  ...              ...            ...          ...
9995          771   39       5  ...                0              0            1
9996          516   35      10  ...                0              0            1
9997          709   36       7  ...                0              1            0
9998          772   42       3  ...                0              0            1
9999          792   28       4  ...                0              1            0

[10000 rows x 13 columns]

In [42]:
Y_train = np.array(df2['Exited']).reshape(-1,1)

In [43]:
Y_train

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]])

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

In [26]:
model = LinearRegression()

In [27]:
model.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
Y_predicted = model.predict(X_train)

In [29]:
print(Y_predicted)

[0.16915251 0.19705027 0.32924767 ... 0.08544639 0.35286023 0.17131045]


In [32]:
model2 = LogisticRegression()

In [44]:
model2.fit(X_train, Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [45]:
Y_predicted2 = model2.predict(X_train)

In [46]:
Y_predicted2

array([0, 0, 0, ..., 0, 0, 0])

In [39]:
from sklearn.metrics import confusion_matrix

In [47]:
confusion_matrix(Y_train, Y_predicted2)

array([[7784,  179],
       [1923,  114]])